checkpoint_dir: "/storage/matt_models/inpainting/"
data_path: "/storage/celebA-HQ/celeba_hq_256"

# Number of code vectors for each phase
num_z_test: 32
num_z_valid: 8
num_z_train: 2
num_z_pca: 50
num_pc: 5
pca_reg_freq: 100

# Data
in_chans: 4
out_chans: 3
im_size: 256
image_size: 256

# Optimizer:
lr: 0.001
beta_1: 0
beta_2: 0.99

# Loss weights
gp_weight: 10
adv_weight: 0.0001

# Training
batch_size: 100
num_epochs: 150
psnr_gain_tol: 0.25